multitenancy_enabled: false

blocks_storage:
  backend: filesystem
  bucket_store:
    sync_dir: /tmp/mimir/tsdb-sync
  filesystem:
    dir: /tmp/mimir/data/tsdb
  tsdb:
    dir: /tmp/mimir/tsdb

compactor:
  data_dir: /tmp/mimir/compactor
  sharding_ring:
    kvstore:
      store: memberlist

distributor:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: memberlist

ingester:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: memberlist
    replication_factor: 1

# ruler:
#   rule_path: /data/ruler
#   alertmanager_url: http://127.0.0.1:8080/alertmanager
#   ring:
#     # Quickly detect unhealthy rulers to speed up the tutorial.
#     heartbeat_period: 2s
#     heartbeat_timeout: 10s

server:
  http_listen_port: 9090
  log_level: error

store_gateway:
  sharding_ring:
    replication_factor: 1